#lang plai

;;; EECS 322 Library of Common Functions -- Test
;;; Geoff Hill <GeoffreyHill2012@u.northwestern.edu>
;;; Spring 2011

(require (file "compiler-lib.rkt"))
(require rackunit)

(check-not-false (label? ':hello))
(check-not-false (label? ':_what5))
(check-not-false (label? ':_2nd_fn))
(check-false (label? 5))
(check-false (label? 'eax))
(check-false (label? ':2nd_fn))

(check-not-false (num? 5))
(check-not-false (num? -8))
(check-false (num? ':label))
(check-false (num? 'ebp))

(check-not-false (n4? 0))
(check-not-false (n4? 96))
(check-not-false (n4? -16))
(check-false (n4? ':label))
(check-false (n4? 'eax))
(check-false (n4? -15))

(check-not-false (aop? '+=))
(check-not-false (aop? '-=))
(check-not-false (aop? '*=))
(check-not-false (aop? '&=))
(check-false (aop? 5))
(check-false (aop? ':label))
(check-false (aop? 'var))
(check-false (aop? '/=))

(check-not-false (sop? '>>=))
(check-not-false (sop? '<<=))
(check-false (sop? 5))
(check-false (sop? ':label))
(check-false (sop? 'var))
(check-false (sop? '>=))

(check-not-false (cmp? '<))
(check-not-false (cmp? '<=))
(check-not-false (cmp? '=))
(check-false (cmp? 5))
(check-false (cmp? ':label))
(check-false (cmp? 'var))
(check-false (cmp? '>))

(check-not-false (L1-sx? 'ecx))
(check-false (L1-sx? 'eax))
(check-false (L1-sx? 'edx))
(check-false (L1-sx? 'ebx))
(check-false (L1-sx? 'esi))
(check-false (L1-sx? 'edi))
(check-false (L1-sx? 'ebp))
(check-false (L1-sx? 'esp))
(check-false (L1-sx? 5))
(check-false (L1-sx? -10))
(check-false (L1-sx? ':label))
(check-false (L1-sx? 'var))

(check-not-false (L1-cx? 'eax))
(check-not-false (L1-cx? 'ecx))
(check-not-false (L1-cx? 'edx))
(check-not-false (L1-cx? 'ebx))
(check-false (L1-cx? 'esi))
(check-false (L1-cx? 'edi))
(check-false (L1-cx? 'ebp))
(check-false (L1-cx? 'esp))
(check-false (L1-cx? 5))
(check-false (L1-cx? -10))
(check-false (L1-cx? ':label))
(check-false (L1-cx? 'var))

(check-not-false (L1-x? 'eax))
(check-not-false (L1-x? 'ecx))
(check-not-false (L1-x? 'edx))
(check-not-false (L1-x? 'ebx))
(check-not-false (L1-x? 'esi))
(check-not-false (L1-x? 'edi))
(check-not-false (L1-x? 'ebp))
(check-not-false (L1-x? 'esp))
(check-false (L1-x? 5))
(check-false (L1-x? -10))
(check-false (L1-x? ':label))
(check-false (L1-x? 'var))

(check-not-false (L1-s? 'eax))
(check-not-false (L1-s? 'ecx))
(check-not-false (L1-s? 'edx))
(check-not-false (L1-s? 'ebx))
(check-not-false (L1-s? 'esi))
(check-not-false (L1-s? 'edi))
(check-not-false (L1-s? 'ebp))
(check-not-false (L1-s? 'esp))
(check-not-false (L1-s? 5))
(check-not-false (L1-s? -10))
(check-not-false (L1-s? ':label))
(check-false (L1-s? 'var))

(check-not-false (L2-x? 'r1))
(check-not-false (L2-x? 'temp0))
(check-not-false (L2-x? 'var))
(check-not-false (L2-x? 'eax))
(check-not-false (L2-x? 'ecx))
(check-not-false (L2-x? 'edx))
(check-not-false (L2-x? 'ebx))
(check-not-false (L2-x? 'esi))
(check-not-false (L2-x? 'edi))
(check-not-false (L2-x? 'ebp))
(check-not-false (L2-x? 'esp))
(check-false (L2-x? 5))
(check-false (L2-x? ':label))
(check-false (L2-x? '=))

(check-not-false (L2-s? 'r1))
(check-not-false (L2-s? 'temp0))
(check-not-false (L2-s? 'var))
(check-not-false (L2-s? 'eax))
(check-not-false (L2-s? 'ecx))
(check-not-false (L2-s? 'edx))
(check-not-false (L2-s? 'ebx))
(check-not-false (L2-s? 'esi))
(check-not-false (L2-s? 'edi))
(check-not-false (L2-s? 'ebp))
(check-not-false (L2-s? 'esp))
(check-not-false (L2-s? ':label))
(check-not-false (L2-s? 5))
(check-false (L2-s? '=))

(check-equal? (asm-format 5) "$5")
(check-equal? (asm-format -11) "$-11")
(check-equal? (asm-format 'eax) "%eax")
(check-equal? (asm-format 'ebp) "%ebp")
(check-equal? (asm-format ':g54) "g54:")
(check-equal? (asm-format ':some_fn) "some_fn:")

(check-equal? (asm-lsb 'eax) "%al")
(check-equal? (asm-lsb 'ebx) "%bl")
(check-equal? (asm-lsb 'ecx) "%cl")
(check-equal? (asm-lsb 'edx) "%dl")

(printf "tests completed~n")
