#lang plai
(print-only-errors #t)

;;; EECS 322 Library of Common Functions -- Test
;;; Geoff Hill <GeoffreyHill2012@u.northwestern.edu>
;;; Spring 2011

(require (file "compiler-lib.rkt"))

(test/pred (label? ':hello) (not/c false?))
(test/pred (label? ':_what5) (not/c false?))
(test/pred (label? ':_2nd_fn) (not/c false?))
(test/pred (label? 5) false?)
(test/pred (label? 'eax) false?)
(test/pred (label? ':2nd_fn) false?)

(test/pred (num? 5) (not/c false?))
(test/pred (num? -8) (not/c false?))
(test/pred (num? ':label) false?)
(test/pred (num? 'ebp) false?)

(test/pred (n4? 0) (not/c false?))
(test/pred (n4? 96) (not/c false?))
(test/pred (n4? -16) (not/c false?))
(test/pred (n4? ':label) false?)
(test/pred (n4? 'eax) false?)
(test/pred (n4? -15) false?)

(test/pred (aop? '+=) (not/c false?))
(test/pred (aop? '-=) (not/c false?))
(test/pred (aop? '*=) (not/c false?))
(test/pred (aop? '&=) (not/c false?))
(test/pred (aop? 5) false?)
(test/pred (aop? ':label) false?)
(test/pred (aop? 'var) false?)
(test/pred (aop? '/=) false?)

(test/pred (sop? '>>=) (not/c false?))
(test/pred (sop? '<<=) (not/c false?))
(test/pred (sop? 5) false?)
(test/pred (sop? ':label) false?)
(test/pred (sop? 'var) false?)
(test/pred (sop? '>=) false?)

(test/pred (cmp? '<) (not/c false?))
(test/pred (cmp? '<=) (not/c false?))
(test/pred (cmp? '=) (not/c false?))
(test/pred (cmp? 5) false?)
(test/pred (cmp? ':label) false?)
(test/pred (cmp? 'var) false?)
(test/pred (cmp? '>) false?)

(test/pred (L1-sx? 'ecx) (not/c false?))
(test/pred (L1-sx? 'eax) false?)
(test/pred (L1-sx? 'edx) false?)
(test/pred (L1-sx? 'ebx) false?)
(test/pred (L1-sx? 'esi) false?)
(test/pred (L1-sx? 'edi) false?)
(test/pred (L1-sx? 'ebp) false?)
(test/pred (L1-sx? 'esp) false?)
(test/pred (L1-sx? 5) false?)
(test/pred (L1-sx? -10) false?)
(test/pred (L1-sx? ':label) false?)
(test/pred (L1-sx? 'var) false?)

(test/pred (L1-cx? 'eax) (not/c false?))
(test/pred (L1-cx? 'ecx) (not/c false?))
(test/pred (L1-cx? 'edx) (not/c false?))
(test/pred (L1-cx? 'ebx) (not/c false?))
(test/pred (L1-cx? 'esi) false?)
(test/pred (L1-cx? 'edi) false?)
(test/pred (L1-cx? 'ebp) false?)
(test/pred (L1-cx? 'esp) false?)
(test/pred (L1-cx? 5) false?)
(test/pred (L1-cx? -10) false?)
(test/pred (L1-cx? ':label) false?)
(test/pred (L1-cx? 'var) false?)

(test/pred (L1-x? 'eax) (not/c false?))
(test/pred (L1-x? 'ecx) (not/c false?))
(test/pred (L1-x? 'edx) (not/c false?))
(test/pred (L1-x? 'ebx) (not/c false?))
(test/pred (L1-x? 'esi) (not/c false?))
(test/pred (L1-x? 'edi) (not/c false?))
(test/pred (L1-x? 'ebp) (not/c false?))
(test/pred (L1-x? 'esp) (not/c false?))
(test/pred (L1-x? 5) false?)
(test/pred (L1-x? -10) false?)
(test/pred (L1-x? ':label) false?)
(test/pred (L1-x? 'var) false?)

(test/pred (L1-s? 'eax) (not/c false?))
(test/pred (L1-s? 'ecx) (not/c false?))
(test/pred (L1-s? 'edx) (not/c false?))
(test/pred (L1-s? 'ebx) (not/c false?))
(test/pred (L1-s? 'esi) (not/c false?))
(test/pred (L1-s? 'edi) (not/c false?))
(test/pred (L1-s? 'ebp) (not/c false?))
(test/pred (L1-s? 'esp) (not/c false?))
(test/pred (L1-s? 5) (not/c false?))
(test/pred (L1-s? -10) (not/c false?))
(test/pred (L1-s? ':label) (not/c false?))
(test/pred (L1-s? 'var) false?)

(test/pred (L2-x? 'r1) (not/c false?))
(test/pred (L2-x? 'temp0) (not/c false?))
(test/pred (L2-x? 'var) (not/c false?))
(test/pred (L2-x? 'eax) (not/c false?))
(test/pred (L2-x? 'ecx) (not/c false?))
(test/pred (L2-x? 'edx) (not/c false?))
(test/pred (L2-x? 'ebx) (not/c false?))
(test/pred (L2-x? 'esi) (not/c false?))
(test/pred (L2-x? 'edi) (not/c false?))
(test/pred (L2-x? 'ebp) (not/c false?))
(test/pred (L2-x? 'esp) (not/c false?))
(test/pred (L2-x? 5) false?)
(test/pred (L2-x? ':label) false?)
(test/pred (L2-x? '=) false?)

(test/pred (L2-s? 'r1) (not/c false?))
(test/pred (L2-s? 'temp0) (not/c false?))
(test/pred (L2-s? 'var) (not/c false?))
(test/pred (L2-s? 'eax) (not/c false?))
(test/pred (L2-s? 'ecx) (not/c false?))
(test/pred (L2-s? 'edx) (not/c false?))
(test/pred (L2-s? 'ebx) (not/c false?))
(test/pred (L2-s? 'esi) (not/c false?))
(test/pred (L2-s? 'edi) (not/c false?))
(test/pred (L2-s? 'ebp) (not/c false?))
(test/pred (L2-s? 'esp) (not/c false?))
(test/pred (L2-s? ':label) (not/c false?))
(test/pred (L2-s? 5) (not/c false?))
(test/pred (L2-s? '=) false?)

(test (asm-format 5) "$5")
(test (asm-format -11) "$-11")
(test (asm-format 'eax) "%eax")
(test (asm-format 'ebp) "%ebp")
(test (asm-format ':g54) "g54:")
(test (asm-format ':some_fn) "some_fn:")

(test (asm-lsb 'eax) "%al")
(test (asm-lsb 'ebx) "%bl")
(test (asm-lsb 'ecx) "%cl")
(test (asm-lsb 'edx) "%dl")

(printf "tests completed~n")
