#!/bin/bash

#RACKET_PATH="/Applications/Racket v5.1/bin/racket"
RACKET_PATH="/opt/racket-5.1/bin/racket"

if [ -z "$1" ];
  then
    echo "Usage: ./graph PROGRAM"
  else
    "$RACKET_PATH" -um "./L2.rkt" "graph" "$1"
fi

