#!/bin/bash

RACKET_PATH="racket"

if [ -x "/opt/racket-5.1/bin/racket" ]
then
  RACKET_PATH="/opt/racket-5.1/bin/racket"
fi

if [ -x "/Applications/Racket v5.1/bin/racket" ]
then
  RACKET_PATH="/Applications/Racket v5.1/bin/racket"
fi

FPREFIX=`echo $RANDOM`

if [ -z "$1" ];
  then
    echo "Usage: ./L1 PROGRAM"
  else
    "$RACKET_PATH" -tm "./L1.rkt" "$1" > $FPREFIX.asm
    as -o $FPREFIX.o $FPREFIX.asm
    gcc4 -O0 -o a.out $FPREFIX.o L1-runtime.c
    chmod +x a.out
    rm -f $FPREFIX.asm $FPREFIX.o
fi

