#!/bin/bash

#RACKET_PATH="/Applications/Racket v5.1/bin/racket"
RACKET_PATH="/opt/racket-5.1/bin/racket"

if [ -z "$1" ];
  then
    echo "Usage: ./L2c PROGRAM"
  else
    "$RACKET_PATH" -tm "./L2.rkt" "compile" "$1"
fi

